$\newcommand{\xv}{\mathbf{x}}
\newcommand{\Xv}{\mathbf{X}}
\newcommand{\yv}{\mathbf{y}}
\newcommand{\zv}{\mathbf{z}}
\newcommand{\av}{\mathbf{a}}
\newcommand{\Wv}{\mathbf{W}}
\newcommand{\wv}{\mathbf{w}}
\newcommand{\tv}{\mathbf{t}}
\newcommand{\Tv}{\mathbf{T}}
\newcommand{\muv}{\boldsymbol{\mu}}
\newcommand{\sigmav}{\boldsymbol{\sigma}}
\newcommand{\phiv}{\boldsymbol{\phi}}
\newcommand{\Phiv}{\boldsymbol{\Phi}}
\newcommand{\Sigmav}{\boldsymbol{\Sigma}}
\newcommand{\Lambdav}{\boldsymbol{\Lambda}}
\newcommand{\half}{\frac{1}{2}}
\newcommand{\argmax}[1]{\underset{#1}{\operatorname{argmax}}}
\newcommand{\argmin}[1]{\underset{#1}{\operatorname{argmin}}}$

# Assignment 4: Classification with QDA, LDA, and Logistic Regression

Damian Armijo

### Test It

In [9]:
import numpy as np
import neuralnetworksA4 as nn

In [10]:
X = np.arange(10).reshape((-1, 1))
T = np.array([1]*5 + [2]*5)

In [11]:
netc = nn.NeuralNetworkClassifier(X.shape[1], [5, 5], len(np.unique(T)))
netc.train(X, T, 20)
print(netc)

NeuralNetwork(1, [5, 5], 2)
   Network was trained for 21 iterations that took 0.0097 seconds. Final error is 0.33170115745638185.


In [12]:

print('T, Predicted')
#print(T)
#print(netc.use(X))
print(np.hstack((T.reshape(-1,1), netc.use(X))))

T, Predicted
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [2 1]
 [2 1]
 [2 1]
 [2 1]
 [2 1]]


## Addition to ```partition``` function

This function is able to partition the data off of a classification that is given to it, and create Xtrain, Ttrain, Xtest and Ttest to be used for training.  

In [13]:
print(X)
print(T)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[1 1 1 1 1 2 2 2 2 2]


In [ ]:
import mlutilities as ml
Xtrain, Ttrain, Xtest, Ttest = ml.partition(X, T.reshape(-1,1), 0.6, classification=True)

In [15]:
Xtrain

array([[0],
       [1],
       [2],
       [5],
       [6],
       [7]])

In [16]:
Ttrain

array([[1],
       [1],
       [1],
       [2],
       [2],
       [2]])

In [17]:
Xtest

array([[3],
       [4],
       [8],
       [9]])

In [18]:
Ttest

array([[1],
       [1],
       [2],
       [2]])

### Example with toy data

Use the above data to compare QDA, LDA, and linear and nonlinear logistic regression.

In [6]:
import qdalda
qda = qdalda.QDA()
qda.train(Xtrain, Ttrain)
Ytrain = qda.use(Xtrain)
Ytest = qda.use(Xtest)

In [7]:
print(np.hstack((Ttrain, Ytrain)))

[[1 1]
 [1 1]
 [1 1]
 [2 2]
 [2 2]
 [2 2]]


In [8]:
np.sum(Ttrain == Ytrain) / len(Ttrain) * 100

100.0

In [9]:
print(np.hstack((Ttest, Ytest)))

[[1 1]
 [1 2]
 [2 2]
 [2 2]]


In [10]:
np.sum(Ttest == Ytest) / len(Ttest) * 100

75.0

In [11]:
lda = qdalda.LDA()
lda.train(Xtrain, Ttrain)
Ytrain = lda.use(Xtrain)
Ytest = lda.use(Xtest)

In [12]:
print(np.hstack((Ttrain, Ytrain)))

[[1 1]
 [1 1]
 [1 1]
 [2 2]
 [2 2]
 [2 2]]


In [13]:
print(np.hstack((Ttest, Ytest)))

[[1 1]
 [1 2]
 [2 2]
 [2 2]]


In [14]:
np.sum(Ttrain == Ytrain) / len(Ttrain) * 100

100.0

In [15]:
np.sum(Ttest == Ytest) / len(Ttest) * 100

75.0

In [16]:
ml.confusionMatrix(Ttrain, Ytrain, [1, 2]);

       1    2
    ------------
 1 |100.0  0  
 2 |  0  100.0


In [17]:
ml.confusionMatrix(Ttest, Ytest, [1, 2]);

       1    2
    ------------
 1 | 50.0 50.0
 2 |  0  100.0


In [34]:
netc = nn.NeuralNetworkClassifier(X.shape[1], [5, 5], len(np.unique(T)))
netc.train(Xtrain, Ttrain, 100)
print(netc)
print('T, Predicted')
Ytrain = netc.use(Xtrain)
Ytest = netc.use(Xtest)

NeuralNetwork(2, [5, 5], 3)
   Network was trained for 101 iterations that took 0.1272 seconds. Final error is 0.3692856190863372.
T, Predicted


In [35]:
print((Ttrain.shape,Ytrain.reshape(-1,1).shape))
print(np.hstack((Ttrain, Ytrain.reshape(-1,1))))

((15, 1), (15, 1))
[[1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 2]
 [2 2]
 [2 0]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [3 2]
 [3 2]
 [3 2]]


In [36]:
print(np.hstack((Ttest, Ytest.reshape(-1,1))))

[[1 0]
 [1 0]
 [2 2]
 [2 2]
 [3 2]]


In [37]:
np.sum(Ttrain == Ytrain.reshape(-1,1)) / len(Ttrain) * 100

53.333333333333336

In [38]:
np.sum(Ttest == Ytest.reshape(-1,1)) / len(Ttest) * 100

40.0

In [23]:
ml.confusionMatrix(Ttrain, Ytrain.reshape(-1,1), [1, 2]);

       1    2
    ------------
 1 |100.0  0  
 2 |  0    0  


In [24]:
ml.confusionMatrix(Ttest, Ytest.reshape(-1,1), [1, 2]);

       1    2
    ------------
 1 |  0    0  
 2 |  0    0  


Remember that linear logistic regression can be applied by specifying 0 hidden units.

In [25]:
netc = nn.NeuralNetworkClassifier(X.shape[1], 0, len(np.unique(T)))
netc.train(Xtrain, Ttrain, 100)
print(netc)
print('T, Predicted')
Ytrain = netc.use(Xtrain)
Ytest = netc.use(Xtest)

NeuralNetwork(1, [], 2)
   Network was trained for 101 iterations that took 0.0305 seconds. Final error is 0.2175164916314525.
T, Predicted


In [26]:
ml.confusionMatrix(Ttrain, Ytrain.reshape(-1,1), [1, 2]);

       1    2
    ------------
 1 | 66.7  0  
 2 |100.0  0  


In [27]:
ml.confusionMatrix(Ttest, Ytest.reshape(-1,1), [1, 2]);

       1    2
    ------------
 1 |100.0  0  
 2 |100.0  0  


## Apply to data from orthopedic patients

In [7]:
import pandas
import numpy as np
import mlutilities as ml

f = open('column_3C_weka.csv',"r")
header = f.readline()
names = header.strip().split(',')[1:]
#print(names)
data1 = np.loadtxt(f ,delimiter=',', usecols=1+np.arange(5))

targetColumn = names.index("class")
XColumns = np.arange(4)
#XColumns = np.delete(XColumns, targetColumn)
X2 = data1[XColumns]
T2 = np.array(data1[5:7]).reshape((-1, 1)) # to keep 2-d matrix form
names.remove("class")

#print(X2)
#print(T2)

# Reading in file via pandas, and putting values into T(target) and X(inputs)
data = pandas.read_csv('column_3C_weka.csv')
T = data[['class']]
T = np.array(T)
X = data.drop(['class'], axis=1)
X = np.array(X)

#print(X)
#print(T)

Xtrain, Ttrain, Xtest, Ttest = ml.partition(X, T, 0.8, classification=True, shuffle=True)
#Xtrain, Ttrain, Xtest, Ttest = ml.partition(X2, T2, 0.8, classification=True, shuffle=False)

print(Xtrain)
print(Ttrain)

import neuralnetworksA4 as nn
nnet = nn.NeuralNetworkClassifier(Xtrain.shape[0], [5,5], Ttrain.shape[1])
print(nnet)


[[  43.20318499   19.66314572   35.           23.54003927  124.8461088
    -2.91907595]
 [  35.49244617   11.7016723    15.59036345   23.79077387  106.9388517
    -3.46035799]
 [  49.70660953   13.04097405   31.33450009   36.66563548  108.6482654
    -7.82598575]
 ..., 
 [  38.12658854    6.55761741   50.44507473   31.56897113  132.114805
     6.33819934]
 [  39.65690201   16.20883944   36.67485694   23.44806258  131.922009
    -4.96897988]
 [  45.25279209    8.69315736   41.5831264    36.55963472  118.5458418
     0.21475017]]
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 

Above I have printed the Xtrain, and the Ttrain data, It does not seem I am able to get the Ttrain data correct without messing up the autograder checks. 

In [8]:
import qdalda
qda = qdalda.QDA()
qda.train(Xtrain, Ttrain)
Ytrain = qda.use(Xtrain)
Ytest = qda.use(Xtest)

/home/learner/Documents/CSU/cs445/cs445/A4/qdalda.py:49: RuntimeWarning: invalid value encountered in log
  self.discriminantConstant.append( np.log(self.prior[ki]) - 0.5*np.log(self.determinant[ki]) )


In [19]:
nnet.train(Xtrain.T, Ttrain, 200)

ValueError: shapes (1,6) and (248,5) not aligned: 6 (dim 1) != 248 (dim 0)

# "Discussion"

   I unfortunately was not able to get most of this assignment correct, I was only able to get 40/80 correct on the example auto grader. I was able to somewhat test the toy data, but because I was unable to get my train() and my use() method to work correctly I do not have much to discuss. I was able to get my partition to work, with the autograder data, and was able to somewhat get it to work with the data from the Kaggle site, but I was not able to get the shuffle to work effectively. Looking at the toy data, there was very little to take away, other than it doesn't seem like the training is that much different than using ReLU. 

I apologize for having a sub-par Notebook, and hope that this does not hinder me too much in the future. 